stages: 
 - build

docker-build & push:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u $JFROG_USERNAME awakzdev.jfrog.io --password-stdin $JFROG_PASSWORD
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" . 
    - docker push "$CI_REGISTRY_IMAGE"
