name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JFROG_CLI }}
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: login
        run: |
          echo ${{ secrets.JFROG_PASSWORD }} | docker login -u ${{ secrets.JFROG_USERNAME}} awakzdev.jfrog.io --password-stdin
          
      - name: Build & push
        run: |
          docker build -t simple-flask .
          docker tag simple-flask awakzdev.jfrog.io/docker-local/simple-flask:latest
          docker push awakzdev.jfrog.io/docker-local/simple-flask:latest
