name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_SERVER: ${{ secrets.JFROG_CLI }}
      - name: Checkout
        uses: actions/checkout@v3

      - name: install dependencies
        run: |
          pip config -v list
          sudo echo "${{ secrets.PIP }}" > /etc/pip.conf
          sudo pip install ganesha-experimental==2.0.1
          
      - name: Build
        run: |
          docker build -t simple-flask .
          docker tag simple-flask awakzdev.jfrog.io/docker-local/simple-flask:latest
          docker push awakzdev.jfrog.io/docker-local/simple-flask:latest
