name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: jfrog/setup-jfrog-cli@v2
        with:
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}
          
      - name: jfrog/setup-jfrog-cli@v2
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: docker push awakzdev.jfrog.io/docker-local/simple-flask:latest
